# Generated by Django 2.2.20 on 2021-06-15 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210615_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_home_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
